### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by fumyou13** [kasuganosoras/cxk-ball#17]
There is a problem in music

**Comment by pippakiwi** [comment]
音乐播放出现问题

**Comment by kasuganosoras** [comment]
因为今天接到大量反馈表示音乐太吵而且过于沙雕，目前已经将音乐删除（

**Comment by kasuganosoras** [comment]
另外一个问题就是涉及音乐版权的事情，所以决定删除 BGM
原曲 “只因你太美” 可在各大音乐平台搜索到

**Comment by fumyou13** [comment]
噢噢

**Comment by Sirenesscn** [comment]
没有音乐瞬间就不带感了

**Comment by fumyou13** [comment]
不带感+1

**Comment by akFace** [comment]
可以放

> 另外一个问题就是涉及音乐版权的事情，所以决定删除 BGM
> 原曲 “只因你太美” 可在各大音乐平台搜索到

可以到b站弄鬼畜声音，版权问题应该不大吧
