### ISSUE TITLE
Bug: 魔法回弹角度&&黄色方块问题

### ISSUE THREAD

**Issue by lrscy** [kasuganosoras/cxk-ball#19]
魔法回弹角度：cxk腰部接球后横向反弹反转。例如：🏀从左侧过来，cxk从右侧接近，撞到腰部后水平方向上🏀先往左一点然后无论碰撞时横向速度多少都以极大速度向右飞去。

偶尔遇上最边上黄色小球碰一次就消失。

手机端，chrome 73.0.3683.90

**Comment by kasuganosoras** [comment]
这不是 Bug，这是特性（雾
当初在制作的时候就发现，高速冲向篮球可以有几率让篮球绕过去，而且还能出现诡异的移动路线……觉得挺好玩的就没去修复
在球的速度非常快撞向黄色方块时，力度最大，因此可以将黄色方块也一次击碎，力度判断：
- Speed 5：需要两次才能击碎黄色方块
- Speed 9：一次就能击碎黄色方块

**Comment by kasuganosoras** [comment]
而且这很像 CXK 的带球旋转（不知道是不是这么叫）那个动作，非常有趣

**Comment by lrscy** [comment]
> 而且这很像 CXK 的带球旋转（不知道是不是这么叫）那个动作，非常有趣

稳中带皮的特性wwwww
