### ISSUE TITLE
蔡徐坤图像不显示？

### ISSUE THREAD

**Issue by processcrash** [kasuganosoras/cxk-ball#2]
蔡徐坤照片不显示

从开始到结束一直未显示

抱歉截图传不上去

**Comment by kasuganosoras** [comment]
可能是你的网络问题，尝试刷新下
或者按 F12 打开浏览器控制台，看看有没有错误提示

**Comment by kasuganosoras** [comment]
已修复，增加图片缓存 4abe86df1fb6d0515e9601f38b49208c0241e74a
