### ISSUE TITLE
火狐报错 

### ISSUE THREAD

**Issue by DevilLostHisSoul** [kasuganosoras/cxk-ball#25]
66.0.3版 Error: Permission denied to access property "__rocketLoaderInlineHandlerProxy"

**Comment by kasuganosoras** [comment]
这个是 CloudFlare 提供的 RocketLoader 插件的问题，不是本项目的锅

**Comment by kasuganosoras** [comment]
目前已经将 RocketLoader 功能关闭，尝试清空缓存然后刷新。
