### ISSUE TITLE
建议把setInterval更换为requestAnimationFrame

### ISSUE THREAD

**Issue by pboymt** [kasuganosoras/cxk-ball#28]
RT，使用requestAnimationFrame的话游戏的帧率更稳定，一般会维持在60fps，setInterval有时候会因为后台出现大量占用CPU资源出现比较严重的卡顿。

**Comment by pboymt** [comment]
翻了一下，我难道是第一个提出技术性建议的issue么:sweat_smile:

**Comment by kasuganosoras** [comment]
可以，有空我测试一下

**Comment by kasuganosoras** [comment]
试了下改为了 `requestAnimationFrame`，但是感觉没有非常明显的性能提升
在 Intel Atom D2550 电脑上都可以顺畅运行，不过在树莓派上有一点卡

**Comment by pboymt** [comment]
@kasuganosoras 树莓派的GPU都是祖传的了，没有良好的WebGL适配。加入requestAnimationFrame之后可以不用自己判定是否离开浏览器就可以自动暂停渲染，节省资源了

**Comment by kasuganosoras** [comment]
已解决
