### ISSUE TITLE
请求全程播放鸡你太美

### ISSUE THREAD

**Issue by cxy475644212** [kasuganosoras/cxk-ball#36]
**这个功能是否与你所遇到的问题有关？**
一句话描述一下你想要的功能或者建议是否是因为你遇到了某些问题

**描述你想要的功能或建议**
用简洁清晰的语句描述你想要什么功能，或者有什么建议

**你是否有可用的备选方案？**
你有没有什么可能可以实现你想要的功能的方法

**附加内容**
任何你觉得可以帮助作者进行改进的内容都可以写到这里

**Comment by kasuganosoras** [comment]
请看 #17
