### ISSUE TITLE
抄别人代码请感谢作者

### ISSUE THREAD

**Issue by Geassu** [kasuganosoras/cxk-ball#37]
抄别人代码标为原创，可耻。不要以为别人看不出来。

**Comment by huulien** [comment]
萧瓜观众表示赞成..

**Comment by kasuganosoras** [comment]
哪里标为原创了？README 里明确写了原项目是 [h5-game-blockBreaker](https://github.com/yangyunhe369/h5-game-blockBreaker)，网页上也标注了原作者，并且我也没有在任何地方说这是我的原创代码，只是 Fork 然后修改而已。

**Comment by Geassu** [comment]
额，那就是原作者抄的。。

**Comment by kasuganosoras** [comment]
？？？
你可能不理解 Fork 的意思吧，Fork 是原项目的一个分支，可以理解为原项目的另一个版本
我只是基于 h5-game-blockBreaker 这个项目做了一些修改，让它变成一个新的游戏而已
底层游戏代码还是原来的作者 yangyunhe369 写的

**Comment by pboymt** [comment]
小鬼跑github当警察了可还行
