### ISSUE TITLE
游戏说明描述的功能无法使用

### ISSUE THREAD

**Issue by Eugene1024** [kasuganosoras/cxk-ball#4]
使用键盘方向键无法移动cxk,按P暂停游戏，再按P居然没法继续游戏，回车让发球后，球掉了就没法玩了 ，而且不知道这个游戏是如何得分的，一发球就是200分

**Comment by kasuganosoras** [comment]
方向键无法移动的话……是台式机还是笔记本的键盘？也许是键位代码不一样导致的
按了 P 是暂停，再按回车就可以继续了，分数的话是打中一个方块 200 分这样子

**Comment by Eugene1024** [comment]
测试环境win7系统    浏览器  chrome73.0.3683.103

**Comment by Eugene1024** [comment]
笔记本电脑

**Comment by kasuganosoras** [comment]
首先打开一个标签页：`about:blank`
打开浏览器控制台，在 Console 页面输入以下内容：
```javascript
window.addEventListener('keydown', function (event) {console.log("Press: " + event.keyCode)});
```
然后在页面上按下方向键的左右键，返回控制台看看输出什么内容

**Comment by Eugene1024** [comment]
undefined

**Comment by kasuganosoras** [comment]
这就很神奇了……
我看看增加 A 和 D 的键位试试

**Comment by kasuganosoras** [comment]
已经增加了 A 和 D 的键位，现在试试
