### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by 15681610858** [kasuganosoras/cxk-ball#46]
gameOver()下应该是globalScore=storageScore，不应该加上之前局的分数

**Comment by kasuganosoras** [comment]
`globalScore` 是游戏的总分，从第一局开始计算分数
`storageScore` 是当前局的分数，每一局开始的时候会清零
比如你在第一局通关了，拿了 14600 分，到第二局拿了 1000 分的时候球掉了，那么总分就是 15600 分

**Comment by 15681610858** [comment]
嗯对，第一次在第一关死亡拿到200分，第二次在第一关死亡拿到200分，但`globalScore`未清零，最终会提示400分。

**Comment by kasuganosoras** [comment]
了解，知道是什么 bug 了

**Comment by kasuganosoras** [comment]
问题已修复
