### ISSUE TITLE
需求建议---关于上线微信小游戏

### ISSUE THREAD

**Issue by 29DCH** [kasuganosoras/cxk-ball#49]
建议上线微信小程序,我以前有弄过微信小游戏这方面的,不过关于这个cxk的游戏不知道能不能被微信官方审核通过......:joy:

**Comment by kasuganosoras** [comment]
本项目使用 MIT 协议开源，你可以自由修改、二次发布，但是注意法律风险（小心 CXK 给你发律师函）
