### ISSUE TITLE
困难模式球速变快了，但是坤坤移速没变快呢

### ISSUE THREAD

**Issue by JoffreyN** [kasuganosoras/cxk-ball#51]
哈哈哈哈还加了特技，还会挥手哈哈哈哈哈哈

**Comment by kasuganosoras** [comment]
不同难度只是球的上下移动速度不同，篮球左右移动速度是不会随着难度而改变的
篮球左右移动速度是根据球接触人物的角度来计算的，人物侧面碰撞球的速度是最快的
