### ISSUE TITLE
非人类模式下得分没有清零

### ISSUE THREAD

**Issue by daddycai** [kasuganosoras/cxk-ball#52]
选择非人类模式，每次结束后得分没有清零，随便玩玩我就这个分了
![image](https://user-images.githubusercontent.com/6211352/56733710-81f9dc80-6793-11e9-9530-65373a904d12.png)

**Comment by kasuganosoras** [comment]
问题已收到，是由于游戏结束后没有清零分数导致的，等我有空修复一下

**Comment by kasuganosoras** [comment]
目前问题已经修复
