### ISSUE TITLE
过关之后，进入不了下一关

### ISSUE THREAD

**Issue by paojianghu** [kasuganosoras/cxk-ball#6]
过关之后一直卡在下一关界面无法新的开始

**Comment by kasuganosoras** [comment]
第几关？如果是第三关就是最后一关，后续我还会做更多的关卡的，敬请期待

**Comment by paojianghu** [comment]
> 第几关？如果是第三关就是最后一关，后续我还会做更多的关卡的，敬请期待

Speed 3

**Comment by kasuganosoras** [comment]
不是。。右上角有写关卡号，具体在哪一关卡了呢

**Comment by paojianghu** [comment]
> 不是。。右上角有写关卡号，具体在哪一关卡了呢

speed 3 关卡1， 完成之后要刷新界面才行

**Comment by kasuganosoras** [comment]
在我这里经过测试无法复现……建议按 f12 打开浏览器控制台看看有没有错误之类的

**Comment by moneytold-zz** [comment]
同，speed2关卡1也无法进入下一关

Failed to load resource: net::ERR_NAME_NOT_RESOLVED   
https://hm.baidu.com/hm.js?5adedb455da362ba577abe2fd8e1095d

Failed to load resource: the server responded with a status of 404 (Not Found)
http://cxk.ssrr.one/favicon.ico

Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
about:blank:1

**Comment by kasuganosoras** [comment]
奇怪……我刚刚测试了很多次都没遇到问题。。。今天玩了几十次了玩的都想吐了。。。

**Comment by huxiangyou** [comment]
同。
我试了几次，大概原因是，通关之后又按了`Enter`，然后再按其他键就都无效了。如果通关后直接按`N`是没问题地直接进入下一关。

**Comment by kasuganosoras** [comment]
> 同。
> 我试了几次，大概原因是，通关之后又按了`Enter`，然后再按其他键就都无效了。如果通关后直接按`N`是没问题地直接进入下一关。

了解了，稍后会修复这个 bug

**Comment by kasuganosoras** [comment]
问题已经修复了，目前通关后按回车不会影响进入下一关

**Comment by huxiangyou** [comment]
别急着关issue啊。其实如果晋级之后按了`P`也会出现相同问题（虽然这个时候不应该按`P`）

**Comment by kasuganosoras** [comment]
噗……我觉得原作者可能完全没有考虑有人可能会在通关的时候乱按……
我去修一下……

**Comment by kasuganosoras** [comment]
已修复，同时还修复了游戏失败后按暂停导致无法重新开始的 bug
