### ISSUE TITLE
Bug:游戏开始后点击“开始游戏”，CXK会向右飘

### ISSUE THREAD

**Issue by TennousuAthena** [kasuganosoras/cxk-ball#60]
**这个功能是否与你所遇到的问题有关？**
如标题，游戏开始后点击“开始游戏”，CXK会向右飘动

**描述你想要的功能或建议**
其实不改也没问题👌

**你是否有可用的备选方案？**
没有。

**附加内容**
这可能是为了适配移动端引起的

**Comment by MikeElderson** [comment]
不仅点开始游戏往右飘，你点任何上边的键都会往右飘

**Comment by MikeElderson** [comment]
closed #24

**Comment by Koukotsukan** [comment]
不仅点开始游戏往右飘，你点屏幕右边任何地方都会往右飘
