### ISSUE TITLE
律师函警告！！

### ISSUE THREAD

**Issue by OneCodeMonkey** [kasuganosoras/cxk-ball#63]
# 律师函

××某：

本律师受中国××资产管理公司委托和北京市盈科律师事务所的指派，依据中华人民共和国有关法律法规，就贵公司拖欠借款不还事宜，特向贵公司发出如下律师函：

你曾向原中国××银行××支行借款本金2000万元，用贵公司的房屋、机器设备等作抵押。2006年9月，中国××银行××支行将该项债权转让给中国 ××资产管理公司。中国××资产管理公司武汉办事处委托荆州市××资产管理有限公司及北京市盈科事务所***律师对该项债权进行清收。截止到2008年2 月20日，该项借款本息余额累计已达3012.64万元。

荆州市××资产管理有限公司接受委托后多次与贵公司进行接洽，商谈如何还款事宜，但贵公司一直没有拿出还款的诚意，致使该事项陷入僵局。现正式向贵公司发出律师函，请贵公司于2008年3月10日之前，采取措施筹措资金，履行还款义务。

**Comment by OneCodeMonkey** [comment]
望作者自重。。

**Comment by kasuganosoras** [comment]
无聊

**Comment by chisaato** [comment]
醒醒,都9102年了.
