### ISSUE TITLE
手机端问题

### ISSUE THREAD

**Issue by ghost** [kasuganosoras/cxk-ball#7]
手机端移动到角落以后就会卡住 望修复

**Comment by kasuganosoras** [comment]
确定操作方式正确吗？操作方法是按屏幕左右来控制人物。
判定移动方向是根据你点击的位置
![img](https://i.imgur.com/2JvTNEn.png)

**Comment by ghost** [comment]
ok的，再试了次，可以了~（不知道为啥第一次就不行x

**Comment by ghost** [comment]
手机端图像显示有问题，Firefox浏览器

**Comment by ghost** [comment]
但是chrome套壳浏览器可以，比如小米自带的
