### ISSUE TITLE
三连击游戏区域仍会造成 Safari 下的放大镜弹框

### ISSUE THREAD

**Issue by GalvinGao** [kasuganosoras/cxk-ball#9]
![7F458A05-D521-4400-AB63-681A730A6321](https://user-images.githubusercontent.com/12567059/56460993-076d3d80-63de-11e9-9174-03b1d08f1ca3.gif)

详见gif；个人暂时没有想出解决方案

**Comment by kasuganosoras** [comment]
已合并 Pr，因为手上没有 iOS 设备，暂时没有办法进行测试（
